steam:
  user: ''
  pass: ''
discord:
  token: ''
  max_retries: 10
frame_data:
  url: 'someurl'
blacklist_file: 'blacklist_file.txt'
stats:
  url: https://bots.discord.pw/api/bots/{bot_id}/stats
  token: 'some_other_token'
admins:
  - ''
common_actions:
  # commands: Help text
  '!frames': >
    Get SFV frame data for the specified char and move. Also
    works with stats of the char like fdash, bdash, throw range etc.
    Use optional parameter -v for more info on the move.
    Usage: ```!frames Ryu cr.mk``` ```!frames Nash phrase``` ```!frames-v Ryu shoryu```
  '!info': >
    'Contacts to get support, provide feedback or fork our code. Shows bot version and some other diagnostic data.'
  '?help': 'Get help on a command. Usage ```?help command_name```'
admin_actions:
  '!blacklist': 'Blacklists a user. Usage ```!blacklist user1 [user2 user3]```'
  '!unblacklist': 'Unblacklists a user. Usage ```!unblacklist user1 [user2 user3]```'
version: "0.0.0"
repo_url: "https://github.com/avivace/sfx-framedata"