steam:
  user: ''
  pass: ''
discord:
  token: ''
  max_retries: 10
frame_data:
  url: 'someurl'
stats:
  url: https://bots.discord.pw/api/bots/{bot_id}/stats
  token: 'some_other_token'
admins:
  - ''
common_actions:
  # commands: Help text
  '!fd': >
    Get SFV frame data for the specified char and move. Also
    works with moves aliases.
    Usage: ```!fd Ryu cr.mk``` ```!fd Ryu m hado```
  '!info': >
    Contacts to get support, provide feedback or fork our code. Shows bot version and some other diagnostic data.
  '!help': 'Get help on a command. Usage ```!help command_name```'
# admin_actions:
version: "0.0.0"
repo_url: "https://github.com/avivace/sfx-framedata"