openapi: "3.0.0"
info:
  version: 0.0.1
  title: SFX API
  description: A sample API that exposes SFV framedata
servers:
  - url: http://TODO.com
paths:
  /characters:
    get:
      tags: [General]
      description: |
        test
      operationId: app.charlist
      responses:
        '200':
          description: List of SFV characters

